# 开发环境
# 配置端口
server:
  port: 8088
  ssl:
    #   classpath是resources目录,classpath*: 通配
    key-store: classpath:jks/ve77.cn.jks
    key-store-password: ve77.cn
    key-store-type: jks
  servlet:
    #  前缀,要以 / 开头
    context-path: /api
    session:
      timeout: 21600

# 配置mysql数据库
spring:
  # 解决 SpringBoot 2.6.0 禁止循环依赖
  main:
    allow-circular-references: true
  datasource:
    dynamic:
      primary: master #设置默认的数据源或者数据源组,默认值即为master
      strict: false #严格匹配数据源,默认false. true未匹配到指定数据源时抛异常,false使用默认数据源

      datasource:
        master:
          url: jdbc:mysql://localhost:3306/blog?serverTimezone=Asia/Shanghai&allowMultiQueries=true
          username: root
          password: mysql7914
          driver-class-name: com.mysql.cj.jdbc.Driver # 3.2.0开始支持SPI可省略此配置
          type: com.zaxxer.hikari.HikariDataSource

        auth:
          url: jdbc:mysql://localhost:3306/auth?serverTimezone=Asia/Shanghai&allowMultiQueries=true
          username: root
          password: mysql7914
          driver-class-name: com.mysql.cj.jdbc.Driver
          type: com.zaxxer.hikari.HikariDataSource

    hikari:
      minimum-idle: 5
      # 空闲连接存活最大时间，默认600000（10分钟）
      idle-timeout: 180000
      # 连接池最大连接数，默认是10
      maximum-pool-size: 10
      # 此属性控制从池返回的连接的默认自动提交行为,默认值：true
      auto-commit: true
      # 连接池名称
      pool-name: MyHikariCP
      # 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      max-lifetime: 1800000
      # 数据库连接超时时间,默认30秒，即30000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  # redis配置
  redis:
    host: localhost
    port: 6379
    password: redis7914

  # es配置 若搜索模式为mysql可删除
  elasticsearch:
    rest:
      uris: localhost:9200

  # 上传图片大小限制
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size:  100MB

# 配置MybatisPlus
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

# 搜索模式 可选 elasticsearch或mysql
search:
  mode: mysql

# 网站前台域名（邮件通知用）
website:
  url: https://ve77.cn/blog
